### ISSUE TITLE
Два staging на тестовом VPS 

### ISSUE THREAD

**Issue by Alexeyvk** [Alexeyvk/dbai#1]
Поставить LAMP, подготовить два окружения
@Shev

**Comment by Alexeyvk** [comment]
reopen for project auto-add automation

**Comment by Alexeyvk** [comment]
Ready fo CR

**Comment by alexey-shev** [comment]
https://dbai.zeleniy-list.od.ua/doika/doika/dashboard/login
https://staging1.dbai.net.ua/doika/doika/dashboard/login
https://staging2.dbai.net.ua/doika/doika/dashboard/login
https://doika4ukraine.adapt-an-app.cf/doika/doika/dashboard/login
